//
//  APIConstant.swift
//  SanskarEP
//
//  Created by Warln on 10/01/22.
//

import Foundation

var BASEURL                = "https://sap.sanskargroup.in"
//var BASEURL              = "https://sap.sanskargroup.in/employee_dev/index.php"
var BASEURL1               = "https://sap.sanskargroup.in/totalbhakti_portal"
let getLogin               = "api_panel/login_app"
let tourApi                = "api_panel/tour_form"
let kLeaveApi              = "api_panel/employee_leave"
let kGuestApi              = "api_panel/guest_request"
let kDayOff                = "api_panel/off_day"
let kleaveReport           = "api_panel/get_leave_requestList"
let kLeaveCancel           = "api_panel/leave_cancellation"
let kplPlanel              = "api_panel/pl_summary_report"
let kVerifyOtp             = "api_panel/email_otp_verification"
let kNewPin                = "api_panel/set_pin"
let kAdvance               = "api_panel/adv_request"
let kPayslip               = "api_panel/pay_slip_request"
let kWfhome                = "api_panel/work_from_home"
let kStat                  = "api_panel/other_request"
let kAprrove               = "api_panel/hod_leave_approval_list"
let kgrant                 = "api_panel/hod_leave_update"
let kattend                = "api_panel/wfh_attendence"
let exList                 = "api_panel/executive_list"
let bookingBase            = "http://bms.sanskargroup.in/sans-api/rest/apiServices"
let santName               = "/getSantName"
let saveBooking            = "rest/apiServices/insRO"
let myBookApi              = "rest/apiServices/getMBLRODetail"
let statData               = "api_panel/get_stationary_list"
let advanceApi             = "api_panel/get_adv_request_list"
let notifyList             = "api_panel/push_history"
let vistorAccept           = "api_panel/visitor_metting"
let removeNote             = "api_panel/remove_push_history"
let guestHistory           = "api_panel/guest_request_list"
let vistorHistory          = "api_panel/getEmp_visitor_list"
let kbdayApi               = "api_panel/birthday"
let bwishApi               = "api-panel/wish-birthday"
let BdaywishesApi          = "api-panel/birthday-wish"
let ktourApi               = "api_panel/get_tour_billing_request"
let ptourApi               = "api_panel/tour_billing_request"
let rbdayApi               = "api-panel/birthday-reply"
let AddEmpApi              = "api_panel/add_employee"
let DeptApi                = "api_panel/department_list"
let LTourApi               = "api_panel/tour_billing_request_ios"
let TDetails               = "api_panel/get_TourRequest_all_detail"
let TDelete                = "api_panel/delete_tourid_billing_request"
let TUpdate                = "api_panel/update_tour_billing_request"
let Tsubmit                = "api_panel/submit_tour_billing_request"
let DetailList             = "api_panel/get_tour_billing_approval_list"
let HODdetails             = "api_panel/get_all_tour_billing_request"
let ProUpdate              = "api_panel/update_profile"
let tupdatet               = "api_panel/get_billing_request_by_tourId"
let tourAppro              = "api_panel/hod_approval_tour_billing_request"
let status                 = "api_panel/get_leave_requestList"
let rejapi                 = "api_panel/get_reject_tour_billing_list"
let srejapi                = "api_panel/reject_tour_billing_request"
let CountApi               = "api_panel/get_count_pending_leave"
let calenderApi            = "api_panel/employee_attendance_graph_detail"
let ChannelApi             = "api_panel/channel_list"
let kathaschedule          = "api_panel/katha_schedule_time"
let kathabookingApi        = "api_panel/katha_booking"
let kathabookingdetailApi  = "api_panel/katha_booking_detail"
let kathatypeApi           = "api_panel/katha_category"
let kathatimingApi         = "api_panel/get_katha_timing_by_katha_category"
let katha_booking_detailApi = "api_panel/katha_booking_detail"
let hodBApprovalApi        = "api_panel/katha_approval"
let kathaApprovedApi       = "api_panel/get-approve-kathalist"
let KathaFilter            = "api_panel/search-kathalist-by-date"
let attendanceApi          = "api_panel/employee_intime_outtime"
let eventApi               = "api_panel/event_detail_backup"
let clientdetailApi        = "api_panel/kathabooking_clientdetail"
let calenderapi            = "api_panel/clientdatail"
let receptionApi           = "api_panel/booking_lead"
let receptionbookingListAPi = "api_panel/booking_lead_list"
let leddetailapi            = "api_panel/booking_lead_list" 
let AssignAPi               = "api_panel/get_data_promo"
let AssignsubmitAPi         = "api_panel/booking_promo_type" 
let AssignPeopleAPi         = "api_panel/assign_booking_detail"
let santnameApi             = "api_panel/exist_guru_list"
let sidebarapi              = "api_panel/side_bar" 
let clientnameApi           = "api_panel/exist_client_list"
let FilterListapi           = "api_panel/get_data_by_date"
let Filterselectapi         = "api_panel/get_date_key"
let SelectAssignapi         = "api_panel/katha_booking_assign"
let RequestListApi          = "api_panel/request_booking"
let HODAssignSubmit         = "api_panel/hod_submit"
let ContentCompleteApi      = "api_panel/empsubmit"
let ContentsubmitApi        = "api_panel/promo_approval"
let PrivacyPolicyApi        = "api_panel/Privacy_Policy"
let EmployeeListApi         = "api_panel/employee"
let scheduleApi             = "api_panel/promolist"
let qcactionApi             = "api_panel/qcapproval"
let CreateMetaApi           = "api_panel/createMetaId" 
let deleteaccountAPi        = "api_panel/delete_emp"
let EmployeeDetailApi       = "api_panel/detailofemp"
let visitorregistration     = "visitor_registration"


// inventory api
let submitedlistapi        = "api_panel/get_inventory_detail"
let requestdetailapi       = "api_panel/get_generate_challan_list"
let misscealaneousapi      = "api_panel/get_miscellaneous_item"
let addchallanmaster       = "api_panel/add_chalan_master"
